name: Release
on:
  push:
    branches: [ main ]
    tags:
      - 'v*' # Se activa al subir un tag como v1.0.0
  workflow_dispatch:

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-22.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      # 1. Configurar Bun
      - name: setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # 2. Instalar dependencias de Rust
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      # 3. Dependencias necesarias para Linux 
      - if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt install libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev

      # 4. Instalar dependencias de frontend
      - name: install dependencies
        run: bun install # o yarn install

      # 5. Construir la app y crear la Release
      - name: build and release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'App Name ${{ github.ref_name }}'
          releaseBody: 'Consulte el registro de cambios para obtener m√°s detalles.'
          releaseDraft: true
          prerelease: false